# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1328c602ad1e67826b1a4bd8e3f12da56d0bb3314e4d8d551a599287ece50914e0104e4f439db6e8809da89761ced0967adf45d5fc512e26ce1b1ee764a2148e

test:
  secret_key_base: 1e987a147814084742466301de10fbc9b7e6e4327c43ab54f82b5cb8a9eea0427346d2230975a9128facd51a267d5b356f2590bbf190ff1c5eeb0d4344120e5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
